### ISSUE TITLE
:sparkles: Make is_ok?/1 and is_err?/1 guards

### ISSUE THREAD

**Issue by hissssst** [linkdd/rustic_result#1]
## Actual Behavior

The functions `is_ok?/1` and `is_err?/1` cannot be used as function guards.

## Desired Behavior

Use the macro `defguard` to define them.

**Comment by linkdd** [comment]
I ended up keeping `is_ok?/1` and `is_err?/1` as-is to avoid breaking changes.

At the moment, those functions will raise an error if supplied with not a result value.

So I added the guards `is_ok_result/1` and `is_err_result/1` (clear different name to avoid confusion), which do not raise errors when supplied with a wrong value.

**Comment by hissssst** [comment]
@linkdd , Having `is_ok?` as a guard wouldn't have broken anything
UPD. Sorry, it would've yep
